# Generated by Django 4.2.21 on 2025-09-26 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_product_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Pieces', 'Pieces')], default='Pieces', max_length=50),
        ),
    ]
