# Generated by Django 5.2.4 on 2025-10-01 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_product_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyproduction',
            old_name='expiry_date',
            new_name='refurbished_date',
        ),
        migrations.RenameField(
            model_name='dailyproduction',
            old_name='batch_number',
            new_name='serial_number',
        ),
        migrations.RemoveField(
            model_name='dailyproduction',
            name='manufactured_date',
        ),
        migrations.RemoveField(
            model_name='dailyproduction',
            name='weight_per_packet',
        ),
    ]
