# Generated by Django 5.2.4 on 2025-10-05 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_expiry_date_dailyproduction_refurbished_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='weight',
        ),
    ]
